name: demo-debezium

services:
  db:
    image: postgres:14.2
    hostname: postgres
    container_name: demo_debezium_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo-debezium
      POSTGRES_USER: demo-debezium
      POSTGRES_PASSWORD: demo-debezium
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "wal_level=logical",
               "-c", "max_replication_slots=4" ]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: demo_debezium_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    hostname: kafka
    container_name: demo_debezium_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 5000
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 29092" ]
      interval: 10s
      timeout: 5s
      retries: 10

  init-kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: demo_debezium_init_kafka
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    volumes:
      - ./etc/docker/kafka/init-kafka-topics.sh:/init-kafka-topics.sh
    command: /init-kafka-topics.sh

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: demo_debezium_kafka_ui
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./etc/docker/kafka/config.yml:/etc/kafkaui/dynamic_config.yaml

  debezium:
    image: debezium/connect:2.6.2.Final
    container_name: demo_debezium_debezium
    restart: unless-stopped
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_connect_configs
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_connect_statuses
    healthcheck:
      test: [ "CMD-SHELL", "curl -sSf http://localhost:8083/connectors || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
